[Database]
user = "${MARIADB_USER}"
password = "${MARIADB_PASSWORD}"
host = "resonite-db"
port = 3306
name = "${MARIADB_DATABASE}"
maxTries = 10
[Server]
host = "${HOST}"
port = ${PORT}
assetsPath = "./assets"
