[Database]
user = "resonite-inventory"
password = "resonitepassword"
host = "resonite-db"
port = 3306
name = "resonite-inventory"
maxTries = 10
[Server]
host = "localhost"
port =  5819
assetsPath = "./assets"
