services:
  app:
    image: ghcr.io/spaceey1/resonite-file-provider:latest
    container_name: resonite-file-provider
    restart: always
    environment:
      BEHIND_PROXY: false
      JWT_SECRET_KEY: "TestkeyPLSCHANGEME!!!!!"
      TZ: "UTC"
    ports:
      - "5819:5819"  # Server. SIDE NODE INTERNAL CONFIG AFFECTS INTERNAL PORT MAKE SURE TO MAKE SAME AS CONFIG PORT
    volumes:
      - ./live-data/assets:/app/assets
      - ./upload-site:/app/upload-site
      - ./live-data/config.toml:/app/config.toml
#      - /etc/resonite-inventory/jwt.key:/run/secrets/jwt.key
    depends_on:
      - db
    networks:
      - resonite-network

  db:
    image: mariadb:lts
    container_name: resonite-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: resonite-inventory
      MARIADB_USER: resonite-inventory
      MARIADB_PASSWORD: resonitepassword
    volumes:
      - ./live-data/mysql-data:/var/lib/mysql
      - ./live-data/mysql-logs:/var/log/mysql
      - ./resonite-inventory-schema.sql:/docker-entrypoint-initdb.d/resonite-inventory-schema.sql
    ports:
      - "3306:3306"
    networks:
      - resonite-network

networks:
  resonite-network:
    driver: bridge
