services:
  app:
    build: .
    container_name: resonite-file-provider
    restart: always
    environment:
      BEHIND_PROXY: false
      JWT_SECRET_KEY: "TestkeyPLSCHANGEME!!!!!"
      TZ: "UTC"
    ports:
      - "5819:5819"  # API port. SIDE NODE INTERNAL CONFIG AFFECTS INTERNAL PORT MAKE SURE TO MAKE SAME AS CONFIG PORT
      - "8080:8080" # Web panel port. if you are reverse proxying you can infact merge this to the root of the reverse proxy, they should not collide with eachother.
    volumes:
      - ./assets:/app/assets
      - ./upload-site:/app/upload-site
#      - /etc/resonite-inventory/jwt.key:/run/secrets/jwt.key
    depends_on:
      - db
    networks:
      - resonite-network

  db:
    image: mysql:8.0
    container_name: resonite-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resonite-inventory
      MYSQL_USER: resonite-inventory
      MYSQL_PASSWORD: resonitepassword
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./resonite-inventory-schema.sql:/docker-entrypoint-initdb.d/resonite-inventory-schema.sql
    ports:
      - "3306:3306"
    networks:
      - resonite-network

networks:
  resonite-network:
    driver: bridge
